artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_name: samsum
  local_data: artifacts/data_ingestion/samsum

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILE: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  local_data: artifacts/data_ingestion/samsum
  tokenizer: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  local_data: artifacts/data_transformation/samsum
  model: google/pegasus-cnn_dailymail

training_arguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1000000
  gradient_accumulation_steps: 16

model_evaluation:
  root_dir: artifacts/model_evaluation
  model: artifacts/model_trainer/pegasus_model
  data: artifacts/data_transformation/samsum
  metrics_file: artifacts/model_evaluation/metrics.csv
  tokenizer: artifacts/model_trainer/tokenizer
